steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/data-workshops/telematics-backend/telematics-backend:latest',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'  
    args: [
      'push',
      'us-central1-docker.pkg.dev/data-workshops/telematics-backend/telematics-backend:latest'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'telematics-backend',
      '--image', 'us-central1-docker.pkg.dev/data-workshops/telematics-backend/telematics-backend:latest',
      '--platform', 'managed',
      '--region', 'us-central1',
    ]

images:
  - 'us-central1-docker.pkg.dev/data-workshops/telematics-backend/telematics-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY